name: Test and Deploy
on:
  push:
    branches:
      - goshujin

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Install Node"
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: "Setup"
        run: npm ci

      - name: "Build Frontend"
        run: npm run build:frontend

      - name: "Test"
        run: |
          npm run fmt
          npm run lint
          npm test

      - name: "Deploy"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          npm run deploy
